# ataegina.config.sh
# Generated by: ataegina init (1.0.1)
#
# Declarative config: ataegina's default hooks read these vars, so you do not
# need to write any bash. (Power users can still define ate_start_* functions
# below to override; see ataegina.config.example.sh.)
#
# detected:
#   frontend: none found
#   backend:  none found
#
# Ports are derived per worktree: FRONT_PORT_BASE+N and BACK_PORT_BASE+N. The
# *_CMD strings reference $FRONTEND_PORT / $BACKEND_PORT / $BACKEND_URL, which
# ataegina exports before running them.

FRONT_PORT_BASE=5173
BACK_PORT_BASE=8000

# TODO: no frontend detected. Set the directory and start command.
# FRONTEND_DIR=frontend
# FRONTEND_CMD='npm run dev -- --port $FRONTEND_PORT'
# FRONTEND_ENV='PUBLIC_API_BASE_URL=$BACKEND_URL'

# TODO: no backend detected. Set the directory and start command.
# BACKEND_DIR=backend
# BACKEND_CMD='your-server --port $BACKEND_PORT'
# BACKEND_ENV='EXTRA_KEY=value'
